
all:
	pdflatex leibowitz-common-lisp-tagging-ontology.tex
	biber leibowitz-common-lisp-tagging-ontology
	pdflatex leibowitz-common-lisp-tagging-ontology.tex
	htlatex leibowitz-common-lisp-tagging-ontology.tex

clean:
	rm -f *.html *.css *.pdf *.4tc *.4ct *.aux *.bcf *.dvi *.idv *.lg *.log *.out *.run.xml *.tmp *.xref *.blg *.bbl
